import numpy as np

PI = np.pi

DEFAULT_VF_LATENT_STATE_DIM = 32
DEFAULT_VF_LATENT_TIME_DIM = 16
DEFAULT_CONDITION_ENCODER_OUTPUT_DIM = 32
DEFAULT_SOURCE_ENCODER_OUTPUT_DIM = 16
DEFAULT_NUM_RESNET_LAYERS = 3
DEFAULT_NUM_TIME_FEATURES = 256
DEFAULT_TIME_FEATURES_MAX_PERIOD = 1_000

DEFAULT_BACKEND = "torch"

DEFAULT_CONDITIONING_LAYER = "concat"

BASE_LEVEL_NAME = "base"
GROUP_LEVEL_NAME = "groups"
CONDITION_LEVEL_NAME = "conditions"

DEFAULT_BATCH_SIZE = 512
DEFAULT_N_GROUPS = 10
DEFAULT_MAX_N_OBS = 10_000
